// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *AccReq_C2S            `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccReq) Reset() {
	*x = AccReq{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccReq) ProtoMessage() {}

func (x *AccReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccReq.ProtoReflect.Descriptor instead.
func (*AccReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccReq) GetC2S() *AccReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type AccRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       int32                  `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"` //RetType，返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *AccRes_S2C            `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccRes) Reset() {
	*x = AccRes{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccRes) ProtoMessage() {}

func (x *AccRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccRes.ProtoReflect.Descriptor instead.
func (*AccRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccRes) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *AccRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *AccRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *AccRes) GetS2C() *AccRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type AccReq_C2S struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserID                uint64                 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`                                  //历史原因，目前已废弃，填0即可
	TrdCategory           *TrdCategory           `protobuf:"varint,2,opt,name=trdCategory,proto3,enum=TrdCategory,oneof" json:"trdCategory,omitempty"` //交易品类，参考 Trd_Common.TrdCategory
	NeedGeneralSecAccount *bool                  `protobuf:"varint,3,opt,name=needGeneralSecAccount,proto3,oneof" json:"needGeneralSecAccount,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AccReq_C2S) Reset() {
	*x = AccReq_C2S{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccReq_C2S) ProtoMessage() {}

func (x *AccReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccReq_C2S.ProtoReflect.Descriptor instead.
func (*AccReq_C2S) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AccReq_C2S) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AccReq_C2S) GetTrdCategory() TrdCategory {
	if x != nil && x.TrdCategory != nil {
		return *x.TrdCategory
	}
	return TrdCategory_TrdCategory_Unknown
}

func (x *AccReq_C2S) GetNeedGeneralSecAccount() bool {
	if x != nil && x.NeedGeneralSecAccount != nil {
		return *x.NeedGeneralSecAccount
	}
	return false
}

type AccRes_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccList       []*TrdAcc              `protobuf:"bytes,1,rep,name=accList,proto3" json:"accList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccRes_S2C) Reset() {
	*x = AccRes_S2C{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccRes_S2C) ProtoMessage() {}

func (x *AccRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccRes_S2C.ProtoReflect.Descriptor instead.
func (*AccRes_S2C) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AccRes_S2C) GetAccList() []*TrdAcc {
	if x != nil {
		return x.AccList
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x1a\fcommon.proto\"\xe1\x01\n" +
	"\x06AccReq\x12\x1d\n" +
	"\x03c2s\x18\x01 \x01(\v2\v.AccReq.C2SR\x03c2s\x1a\xb7\x01\n" +
	"\x03C2S\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x04R\x06userID\x123\n" +
	"\vtrdCategory\x18\x02 \x01(\x0e2\f.TrdCategoryH\x00R\vtrdCategory\x88\x01\x01\x129\n" +
	"\x15needGeneralSecAccount\x18\x03 \x01(\bH\x01R\x15needGeneralSecAccount\x88\x01\x01B\x0e\n" +
	"\f_trdCategoryB\x18\n" +
	"\x16_needGeneralSecAccount\"\xcb\x01\n" +
	"\x06AccRes\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12\"\n" +
	"\x03s2c\x18\x04 \x01(\v2\v.AccRes.S2CH\x02R\x03s2c\x88\x01\x01\x1a(\n" +
	"\x03S2C\x12!\n" +
	"\aaccList\x18\x01 \x03(\v2\a.TrdAccR\aaccListB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2cB\tZ\afutu/pbb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_proto_goTypes = []any{
	(*AccReq)(nil),     // 0: AccReq
	(*AccRes)(nil),     // 1: AccRes
	(*AccReq_C2S)(nil), // 2: AccReq.C2S
	(*AccRes_S2C)(nil), // 3: AccRes.S2C
	(TrdCategory)(0),   // 4: TrdCategory
	(*TrdAcc)(nil),     // 5: TrdAcc
}
var file_account_proto_depIdxs = []int32{
	2, // 0: AccReq.c2s:type_name -> AccReq.C2S
	3, // 1: AccRes.s2c:type_name -> AccRes.S2C
	4, // 2: AccReq.C2S.trdCategory:type_name -> TrdCategory
	5, // 3: AccRes.S2C.accList:type_name -> TrdAcc
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	file_common_proto_init()
	file_account_proto_msgTypes[1].OneofWrappers = []any{}
	file_account_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
