// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: base.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * 初始化请求
type InitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *InitReq_C2S           `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitReq) Reset() {
	*x = InitReq{}
	mi := &file_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReq) ProtoMessage() {}

func (x *InitReq) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReq.ProtoReflect.Descriptor instead.
func (*InitReq) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *InitReq) GetC2S() *InitReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

// * 初始化响应
type InitRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       int32                  `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"`
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *InitRes_S2C           `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRes) Reset() {
	*x = InitRes{}
	mi := &file_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRes) ProtoMessage() {}

func (x *InitRes) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRes.ProtoReflect.Descriptor instead.
func (*InitRes) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *InitRes) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *InitRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *InitRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *InitRes) GetS2C() *InitRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

// * 心跳检测：ping
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *Ping_C2S              `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

func (x *Ping) GetC2S() *Ping_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

// * 心跳响应
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       int32                  `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"`
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *Pong_S2C              `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *Pong) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *Pong) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *Pong) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *Pong) GetS2C() *Pong_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type InitReq_C2S struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * 客户端版本号，clientVer = "."以前的数 * 100 + "."以后的，举例：1.1版本的 clientVer 为1 * 100 + 1 = 101，2.21版本为2 * 100 + 21 = 221
	ClientVer int32 `protobuf:"varint,1,opt,name=clientVer,proto3" json:"clientVer,omitempty"`
	// * 客户端唯一标识，无生具体生成规则，客户端自己保证唯一性即可
	ClientID string `protobuf:"bytes,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	// * 此连接是否接收市场状态、交易需要重新解锁等等事件通知，true 代表接收，OpenD 就会向此连接推送这些通知，反之 false 代表不接收不推送如果通信要加密，首先得在 OpenD 和客户端都配置 RSA 密钥，不配置始终不加密
	RecvNotify *bool `protobuf:"varint,3,opt,name=recvNotify,proto3,oneof" json:"recvNotify,omitempty"`
	// *
	// 如果配置了 RSA 密钥且指定的加密算法不为 PacketEncAlgo_None 则加密(即便这里不设置，配置了 RSA 密钥，也会采用默认加密方式)，默认采用 FTAES_ECB 算法
	// 指定包加密算法，参见 Common.PacketEncAlgo 的枚举定义
	PacketEncAlgo *int32 `protobuf:"varint,4,opt,name=packetEncAlgo,proto3,oneof" json:"packetEncAlgo,omitempty"`
	// *指定这条连接上的推送协议格式，若不指定则使用 push_proto_type 配置项
	PushProtoFmt  *int32 `protobuf:"varint,5,opt,name=pushProtoFmt,proto3,oneof" json:"pushProtoFmt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitReq_C2S) Reset() {
	*x = InitReq_C2S{}
	mi := &file_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitReq_C2S) ProtoMessage() {}

func (x *InitReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitReq_C2S.ProtoReflect.Descriptor instead.
func (*InitReq_C2S) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InitReq_C2S) GetClientVer() int32 {
	if x != nil {
		return x.ClientVer
	}
	return 0
}

func (x *InitReq_C2S) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *InitReq_C2S) GetRecvNotify() bool {
	if x != nil && x.RecvNotify != nil {
		return *x.RecvNotify
	}
	return false
}

func (x *InitReq_C2S) GetPacketEncAlgo() int32 {
	if x != nil && x.PacketEncAlgo != nil {
		return *x.PacketEncAlgo
	}
	return 0
}

func (x *InitReq_C2S) GetPushProtoFmt() int32 {
	if x != nil && x.PushProtoFmt != nil {
		return *x.PushProtoFmt
	}
	return 0
}

type InitRes_S2C struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// * OpenD 的版本号
	ServerVer int32 `protobuf:"varint,1,opt,name=serverVer,proto3" json:"serverVer,omitempty"`
	// * OpenD 登录的用户 ID
	LoginUserID uint64 `protobuf:"varint,2,opt,name=loginUserID,proto3" json:"loginUserID,omitempty"`
	// * 此连接的连接 ID，连接的唯一标识
	ConnID uint64 `protobuf:"varint,3,opt,name=connID,proto3" json:"connID,omitempty"`
	// * 此连接后续 AES 加密通信的 Key，固定为16字节长字符串
	ConnAESKey string `protobuf:"bytes,4,opt,name=connAESKey,proto3" json:"connAESKey,omitempty"`
	// * 心跳保活间隔
	KeepAliveInterval int32 `protobuf:"varint,5,opt,name=keepAliveInterval,proto3" json:"keepAliveInterval,omitempty"`
	// * AES 加密通信 CBC 加密模式的 iv，固定为16字节长字符串
	AesCBCiv      *string `protobuf:"bytes,6,opt,name=aesCBCiv,proto3,oneof" json:"aesCBCiv,omitempty"` //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRes_S2C) Reset() {
	*x = InitRes_S2C{}
	mi := &file_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRes_S2C) ProtoMessage() {}

func (x *InitRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRes_S2C.ProtoReflect.Descriptor instead.
func (*InitRes_S2C) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitRes_S2C) GetServerVer() int32 {
	if x != nil {
		return x.ServerVer
	}
	return 0
}

func (x *InitRes_S2C) GetLoginUserID() uint64 {
	if x != nil {
		return x.LoginUserID
	}
	return 0
}

func (x *InitRes_S2C) GetConnID() uint64 {
	if x != nil {
		return x.ConnID
	}
	return 0
}

func (x *InitRes_S2C) GetConnAESKey() string {
	if x != nil {
		return x.ConnAESKey
	}
	return ""
}

func (x *InitRes_S2C) GetKeepAliveInterval() int32 {
	if x != nil {
		return x.KeepAliveInterval
	}
	return 0
}

func (x *InitRes_S2C) GetAesCBCiv() string {
	if x != nil && x.AesCBCiv != nil {
		return *x.AesCBCiv
	}
	return ""
}

type Ping_C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping_C2S) Reset() {
	*x = Ping_C2S{}
	mi := &file_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping_C2S) ProtoMessage() {}

func (x *Ping_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping_C2S.ProtoReflect.Descriptor instead.
func (*Ping_C2S) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Ping_C2S) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Pong_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong_S2C) Reset() {
	*x = Pong_S2C{}
	mi := &file_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong_S2C) ProtoMessage() {}

func (x *Pong_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong_S2C.ProtoReflect.Descriptor instead.
func (*Pong_S2C) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Pong_S2C) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\"\x96\x02\n" +
	"\aInitReq\x12\x1e\n" +
	"\x03c2s\x18\x01 \x01(\v2\f.InitReq.C2SR\x03c2s\x1a\xea\x01\n" +
	"\x03C2S\x12\x1c\n" +
	"\tclientVer\x18\x01 \x01(\x05R\tclientVer\x12\x1a\n" +
	"\bclientID\x18\x02 \x01(\tR\bclientID\x12#\n" +
	"\n" +
	"recvNotify\x18\x03 \x01(\bH\x00R\n" +
	"recvNotify\x88\x01\x01\x12)\n" +
	"\rpacketEncAlgo\x18\x04 \x01(\x05H\x01R\rpacketEncAlgo\x88\x01\x01\x12'\n" +
	"\fpushProtoFmt\x18\x05 \x01(\x05H\x02R\fpushProtoFmt\x88\x01\x01B\r\n" +
	"\v_recvNotifyB\x10\n" +
	"\x0e_packetEncAlgoB\x0f\n" +
	"\r_pushProtoFmt\"\xff\x02\n" +
	"\aInitRes\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12#\n" +
	"\x03s2c\x18\x04 \x01(\v2\f.InitRes.S2CH\x02R\x03s2c\x88\x01\x01\x1a\xd9\x01\n" +
	"\x03S2C\x12\x1c\n" +
	"\tserverVer\x18\x01 \x01(\x05R\tserverVer\x12 \n" +
	"\vloginUserID\x18\x02 \x01(\x04R\vloginUserID\x12\x16\n" +
	"\x06connID\x18\x03 \x01(\x04R\x06connID\x12\x1e\n" +
	"\n" +
	"connAESKey\x18\x04 \x01(\tR\n" +
	"connAESKey\x12,\n" +
	"\x11keepAliveInterval\x18\x05 \x01(\x05R\x11keepAliveInterval\x12\x1f\n" +
	"\baesCBCiv\x18\x06 \x01(\tH\x00R\baesCBCiv\x88\x01\x01B\v\n" +
	"\t_aesCBCivB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2c\">\n" +
	"\x04Ping\x12\x1b\n" +
	"\x03c2s\x18\x01 \x01(\v2\t.Ping.C2SR\x03c2s\x1a\x19\n" +
	"\x03C2S\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"\xb8\x01\n" +
	"\x04Pong\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12 \n" +
	"\x03s2c\x18\x04 \x01(\v2\t.Pong.S2CH\x02R\x03s2c\x88\x01\x01\x1a\x19\n" +
	"\x03S2C\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04timeB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2cB\tZ\afutu/pbb\x06proto3"

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData []byte
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)))
	})
	return file_base_proto_rawDescData
}

var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_base_proto_goTypes = []any{
	(*InitReq)(nil),     // 0: InitReq
	(*InitRes)(nil),     // 1: InitRes
	(*Ping)(nil),        // 2: Ping
	(*Pong)(nil),        // 3: Pong
	(*InitReq_C2S)(nil), // 4: InitReq.C2S
	(*InitRes_S2C)(nil), // 5: InitRes.S2C
	(*Ping_C2S)(nil),    // 6: Ping.C2S
	(*Pong_S2C)(nil),    // 7: Pong.S2C
}
var file_base_proto_depIdxs = []int32{
	4, // 0: InitReq.c2s:type_name -> InitReq.C2S
	5, // 1: InitRes.s2c:type_name -> InitRes.S2C
	6, // 2: Ping.c2s:type_name -> Ping.C2S
	7, // 3: Pong.s2c:type_name -> Pong.S2C
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	file_base_proto_msgTypes[1].OneofWrappers = []any{}
	file_base_proto_msgTypes[3].OneofWrappers = []any{}
	file_base_proto_msgTypes[4].OneofWrappers = []any{}
	file_base_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
