// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *订单费用请求
type FeeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *FeeReq_C2S            `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeReq) Reset() {
	*x = FeeReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeReq) ProtoMessage() {}

func (x *FeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeReq.ProtoReflect.Descriptor instead.
func (*FeeReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *FeeReq) GetC2S() *FeeReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

// *订单费用响应
type FeeRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       RetType     `protobuf:"varint,1,opt,name=retType,proto3,enum=common.RetType" json:"retType,omitempty"`
	RetMsg        *string     `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32      `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *FeeRes_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeRes) Reset() {
	*x = FeeRes{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeRes) ProtoMessage() {}

func (x *FeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeRes.ProtoReflect.Descriptor instead.
func (*FeeRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *FeeRes) GetRetType() RetType {
	if x != nil {
		return x.RetType
	}
	return RetType_RetType_Succeed
}

func (x *FeeRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *FeeRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *FeeRes) GetS2C() *FeeRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

// * 订单推送
type NotifyOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       RetType          `protobuf:"varint,1,opt,name=retType,proto3,enum=common.RetType" json:"retType,omitempty"`
	RetMsg        *string          `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32           `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *NotifyOrder_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrder) Reset() {
	*x = NotifyOrder{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrder) ProtoMessage() {}

func (x *NotifyOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrder.ProtoReflect.Descriptor instead.
func (*NotifyOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyOrder) GetRetType() RetType {
	if x != nil {
		return x.RetType
	}
	return RetType_RetType_Succeed
}

func (x *NotifyOrder) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *NotifyOrder) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *NotifyOrder) GetS2C() *NotifyOrder_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

// * 成交订单
type NotifyOrderFill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       RetType              `protobuf:"varint,1,opt,name=retType,proto3,enum=common.RetType" json:"retType,omitempty"`
	RetMsg        *string              `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32               `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *NotifyOrderFill_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderFill) Reset() {
	*x = NotifyOrderFill{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderFill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderFill) ProtoMessage() {}

func (x *NotifyOrderFill) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderFill.ProtoReflect.Descriptor instead.
func (*NotifyOrderFill) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyOrderFill) GetRetType() RetType {
	if x != nil {
		return x.RetType
	}
	return RetType_RetType_Succeed
}

func (x *NotifyOrderFill) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *NotifyOrderFill) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *NotifyOrderFill) GetS2C() *NotifyOrderFill_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *CreateOrderReq_C2S    `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderReq) GetC2S() *CreateOrderReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

type CreateOrderRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       RetType             `protobuf:"varint,1,opt,name=retType,proto3,enum=common.RetType" json:"retType,omitempty"`
	RetMsg        *string             `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32              `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *CreateOrderRes_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRes) GetRetType() RetType {
	if x != nil {
		return x.RetType
	}
	return RetType_RetType_Succeed
}

func (x *CreateOrderRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *CreateOrderRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *CreateOrderRes) GetS2C() *CreateOrderRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type FeeReq_C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`               //交易公共参数头
	OrderIdExList []string               `protobuf:"bytes,2,rep,name=orderIdExList,proto3" json:"orderIdExList,omitempty"` // 服务器订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeReq_C2S) Reset() {
	*x = FeeReq_C2S{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeReq_C2S) ProtoMessage() {}

func (x *FeeReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeReq_C2S.ProtoReflect.Descriptor instead.
func (*FeeReq_C2S) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FeeReq_C2S) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FeeReq_C2S) GetOrderIdExList() []string {
	if x != nil {
		return x.OrderIdExList
	}
	return nil
}

type FeeRes_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`             //交易公共参数头
	OrderFeeList  []*OrderFee            `protobuf:"bytes,2,rep,name=orderFeeList,proto3" json:"orderFeeList,omitempty"` //订单费用列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeRes_S2C) Reset() {
	*x = FeeRes_S2C{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeRes_S2C) ProtoMessage() {}

func (x *FeeRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeRes_S2C.ProtoReflect.Descriptor instead.
func (*FeeRes_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FeeRes_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FeeRes_S2C) GetOrderFeeList() []*OrderFee {
	if x != nil {
		return x.OrderFeeList
	}
	return nil
}

type NotifyOrder_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` //交易公共参数头
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`   //订单结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrder_S2C) Reset() {
	*x = NotifyOrder_S2C{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrder_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrder_S2C) ProtoMessage() {}

func (x *NotifyOrder_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrder_S2C.ProtoReflect.Descriptor instead.
func (*NotifyOrder_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NotifyOrder_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NotifyOrder_S2C) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type NotifyOrderFill_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` //交易公共参数头
	Order         *OrderFill             `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`   //成交结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrderFill_S2C) Reset() {
	*x = NotifyOrderFill_S2C{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrderFill_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrderFill_S2C) ProtoMessage() {}

func (x *NotifyOrderFill_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrderFill_S2C.ProtoReflect.Descriptor instead.
func (*NotifyOrderFill_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3, 0}
}

func (x *NotifyOrderFill_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NotifyOrderFill_S2C) GetOrder() *OrderFill {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateOrderReq_C2S struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PacketID  *PacketID              `protobuf:"bytes,1,opt,name=packetID,proto3" json:"packetID,omitempty"`    //交易写操作防重放攻击
	Header    *TrdHeader             `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`        //交易公共参数头
	TrdSide   int32                  `protobuf:"varint,3,opt,name=trdSide,proto3" json:"trdSide,omitempty"`     //交易方向，参见 Trd_Common.TrdSide 的枚举定义
	OrderType int32                  `protobuf:"varint,4,opt,name=orderType,proto3" json:"orderType,omitempty"` //订单类型，参见 Trd_Common.OrderType 的枚举定义
	Code      string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`            //代码，港股必须是5位数字，A 股必须是6位数字，美股没限制
	Qty       float64                `protobuf:"fixed64,6,opt,name=qty,proto3" json:"qty,omitempty"`            //数量，期权单位是"张"（精确到小数点后 0 位，超出部分会被舍弃。期权期货单位是"张"）
	Price     *float64               `protobuf:"fixed64,7,opt,name=price,proto3,oneof" json:"price,omitempty"`  //价格，（证券账户精确到小数点后 3 位，期货账户精确到小数点后 9 位，超出部分会被舍弃）
	// 以下2个为调整价格使用，都传才有效，对港、A 股有意义，因为港股有价位，A 股2位精度，美股可不传
	AdjustPrice        *bool        `protobuf:"varint,8,opt,name=adjustPrice,proto3,oneof" json:"adjustPrice,omitempty"`                          //是否调整价格，如果价格不合法，是否调整到合法价位，true 调整，false 不调整。如果价格不合法又不允许调整，则会返回错误
	AdjustSideAndLimit *float64     `protobuf:"fixed64,9,opt,name=adjustSideAndLimit,proto3,oneof" json:"adjustSideAndLimit,omitempty"`           //调整方向和调整幅度百分比限制，正数代表向上调整，负数代表向下调整，具体值代表调整幅度限制，如：0.015代表向上调整且幅度不超过1.5%；-0.01代表向下调整且幅度不超过1%
	SecMarket          *int32       `protobuf:"varint,10,opt,name=secMarket,proto3,oneof" json:"secMarket,omitempty"`                             //证券所属市场，参见 TrdSecMarket 的枚举定义
	Remark             *string      `protobuf:"bytes,11,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                                    //用户备注字符串，最多只能传64字节。可用于标识订单唯一信息等，下单填上，订单结构就会带上。
	TimeInForce        *TimeInForce `protobuf:"varint,12,opt,name=timeInForce,proto3,enum=common.TimeInForce,oneof" json:"timeInForce,omitempty"` //订单有效期限，参见 TrdCommon.TimeInForce 的枚举定义（香港市场、A 股市场和环球期货的市价单，仅支持当日有效）
	FillOutsideRTH     *bool        `protobuf:"varint,13,opt,name=fillOutsideRTH,proto3,oneof" json:"fillOutsideRTH,omitempty"`                   //是否允许盘前盘后成交（仅用于美股，且盘前盘后时段不支持市价单）。默认 false
	AuxPrice           *float64     `protobuf:"fixed64,14,opt,name=auxPrice,proto3,oneof" json:"auxPrice,omitempty"`                              //触发价格
	TrailType          *int32       `protobuf:"varint,15,opt,name=trailType,proto3,oneof" json:"trailType,omitempty"`                             //跟踪类型, 参见Trd_Common.TrailType的枚举定义
	TrailValue         *float64     `protobuf:"fixed64,16,opt,name=trailValue,proto3,oneof" json:"trailValue,omitempty"`                          //跟踪金额/百分比
	TrailSpread        *float64     `protobuf:"fixed64,17,opt,name=trailSpread,proto3,oneof" json:"trailSpread,omitempty"`                        //指定价差
	Session            *int32       `protobuf:"varint,18,opt,name=session,proto3,oneof" json:"session,omitempty"`                                 //美股订单时段, 参见Common.Session的枚举定义
	PositionID         *uint64      `protobuf:"varint,19,opt,name=positionID,proto3,oneof" json:"positionID,omitempty"`                           //持仓ID，JP券商平仓时使用
	ExpireTime         *string      `protobuf:"bytes,20,opt,name=expireTime,proto3,oneof" json:"expireTime,omitempty"`                            //订单到期时间，仅在timeInForce为GTD时有效
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateOrderReq_C2S) Reset() {
	*x = CreateOrderReq_C2S{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq_C2S) ProtoMessage() {}

func (x *CreateOrderReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq_C2S.ProtoReflect.Descriptor instead.
func (*CreateOrderReq_C2S) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateOrderReq_C2S) GetPacketID() *PacketID {
	if x != nil {
		return x.PacketID
	}
	return nil
}

func (x *CreateOrderReq_C2S) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateOrderReq_C2S) GetTrdSide() int32 {
	if x != nil {
		return x.TrdSide
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateOrderReq_C2S) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetAdjustPrice() bool {
	if x != nil && x.AdjustPrice != nil {
		return *x.AdjustPrice
	}
	return false
}

func (x *CreateOrderReq_C2S) GetAdjustSideAndLimit() float64 {
	if x != nil && x.AdjustSideAndLimit != nil {
		return *x.AdjustSideAndLimit
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetSecMarket() int32 {
	if x != nil && x.SecMarket != nil {
		return *x.SecMarket
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *CreateOrderReq_C2S) GetTimeInForce() TimeInForce {
	if x != nil && x.TimeInForce != nil {
		return *x.TimeInForce
	}
	return TimeInForce_TimeInForce_DAY
}

func (x *CreateOrderReq_C2S) GetFillOutsideRTH() bool {
	if x != nil && x.FillOutsideRTH != nil {
		return *x.FillOutsideRTH
	}
	return false
}

func (x *CreateOrderReq_C2S) GetAuxPrice() float64 {
	if x != nil && x.AuxPrice != nil {
		return *x.AuxPrice
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetTrailType() int32 {
	if x != nil && x.TrailType != nil {
		return *x.TrailType
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetTrailValue() float64 {
	if x != nil && x.TrailValue != nil {
		return *x.TrailValue
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetTrailSpread() float64 {
	if x != nil && x.TrailSpread != nil {
		return *x.TrailSpread
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetSession() int32 {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetPositionID() uint64 {
	if x != nil && x.PositionID != nil {
		return *x.PositionID
	}
	return 0
}

func (x *CreateOrderReq_C2S) GetExpireTime() string {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return ""
}

type CreateOrderRes_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`             //交易公共参数头
	OrderID       *uint64                `protobuf:"varint,2,opt,name=orderID,proto3,oneof" json:"orderID,omitempty"`    //订单号
	OrderIDEx     *string                `protobuf:"bytes,3,opt,name=orderIDEx,proto3,oneof" json:"orderIDEx,omitempty"` //表示服务器订单id，可以用来代替orderID，和orderID二选一
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes_S2C) Reset() {
	*x = CreateOrderRes_S2C{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes_S2C) ProtoMessage() {}

func (x *CreateOrderRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes_S2C.ProtoReflect.Descriptor instead.
func (*CreateOrderRes_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateOrderRes_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CreateOrderRes_S2C) GetOrderID() uint64 {
	if x != nil && x.OrderID != nil {
		return *x.OrderID
	}
	return 0
}

func (x *CreateOrderRes_S2C) GetOrderIDEx() string {
	if x != nil && x.OrderIDEx != nil {
		return *x.OrderIDEx
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x1a\fcommon.proto\"\x7f\n" +
	"\x06FeeReq\x12\x1d\n" +
	"\x03c2s\x18\x01 \x01(\v2\v.FeeReq.C2SR\x03c2s\x1aV\n" +
	"\x03C2S\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12$\n" +
	"\rorderIdExList\x18\x02 \x03(\tR\rorderIdExList\"\x9a\x02\n" +
	"\x06FeeRes\x12)\n" +
	"\aretType\x18\x01 \x01(\x0e2\x0f.common.RetTypeR\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12\"\n" +
	"\x03s2c\x18\x04 \x01(\v2\v.FeeRes.S2CH\x02R\x03s2c\x88\x01\x01\x1af\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x124\n" +
	"\forderFeeList\x18\x02 \x03(\v2\x10.common.OrderFeeR\forderFeeListB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2c\"\x93\x02\n" +
	"\vNotifyOrder\x12)\n" +
	"\aretType\x18\x01 \x01(\x0e2\x0f.common.RetTypeR\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12'\n" +
	"\x03s2c\x18\x04 \x01(\v2\x10.NotifyOrder.S2CH\x02R\x03s2c\x88\x01\x01\x1aU\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12#\n" +
	"\x05order\x18\x02 \x01(\v2\r.common.OrderR\x05orderB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2c\"\x9f\x02\n" +
	"\x0fNotifyOrderFill\x12)\n" +
	"\aretType\x18\x01 \x01(\x0e2\x0f.common.RetTypeR\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12+\n" +
	"\x03s2c\x18\x04 \x01(\v2\x14.NotifyOrderFill.S2CH\x02R\x03s2c\x88\x01\x01\x1aY\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12'\n" +
	"\x05order\x18\x02 \x01(\v2\x11.common.OrderFillR\x05orderB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2c\"\xe0\a\n" +
	"\x0eCreateOrderReq\x12%\n" +
	"\x03c2s\x18\x01 \x01(\v2\x13.CreateOrderReq.C2SR\x03c2s\x1a\xa6\a\n" +
	"\x03C2S\x12,\n" +
	"\bpacketID\x18\x01 \x01(\v2\x10.common.PacketIDR\bpacketID\x12)\n" +
	"\x06header\x18\x02 \x01(\v2\x11.common.TrdHeaderR\x06header\x12\x18\n" +
	"\atrdSide\x18\x03 \x01(\x05R\atrdSide\x12\x1c\n" +
	"\torderType\x18\x04 \x01(\x05R\torderType\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x10\n" +
	"\x03qty\x18\x06 \x01(\x01R\x03qty\x12\x19\n" +
	"\x05price\x18\a \x01(\x01H\x00R\x05price\x88\x01\x01\x12%\n" +
	"\vadjustPrice\x18\b \x01(\bH\x01R\vadjustPrice\x88\x01\x01\x123\n" +
	"\x12adjustSideAndLimit\x18\t \x01(\x01H\x02R\x12adjustSideAndLimit\x88\x01\x01\x12!\n" +
	"\tsecMarket\x18\n" +
	" \x01(\x05H\x03R\tsecMarket\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\v \x01(\tH\x04R\x06remark\x88\x01\x01\x12:\n" +
	"\vtimeInForce\x18\f \x01(\x0e2\x13.common.TimeInForceH\x05R\vtimeInForce\x88\x01\x01\x12+\n" +
	"\x0efillOutsideRTH\x18\r \x01(\bH\x06R\x0efillOutsideRTH\x88\x01\x01\x12\x1f\n" +
	"\bauxPrice\x18\x0e \x01(\x01H\aR\bauxPrice\x88\x01\x01\x12!\n" +
	"\ttrailType\x18\x0f \x01(\x05H\bR\ttrailType\x88\x01\x01\x12#\n" +
	"\n" +
	"trailValue\x18\x10 \x01(\x01H\tR\n" +
	"trailValue\x88\x01\x01\x12%\n" +
	"\vtrailSpread\x18\x11 \x01(\x01H\n" +
	"R\vtrailSpread\x88\x01\x01\x12\x1d\n" +
	"\asession\x18\x12 \x01(\x05H\vR\asession\x88\x01\x01\x12#\n" +
	"\n" +
	"positionID\x18\x13 \x01(\x04H\fR\n" +
	"positionID\x88\x01\x01\x12#\n" +
	"\n" +
	"expireTime\x18\x14 \x01(\tH\rR\n" +
	"expireTime\x88\x01\x01B\b\n" +
	"\x06_priceB\x0e\n" +
	"\f_adjustPriceB\x15\n" +
	"\x13_adjustSideAndLimitB\f\n" +
	"\n" +
	"_secMarketB\t\n" +
	"\a_remarkB\x0e\n" +
	"\f_timeInForceB\x11\n" +
	"\x0f_fillOutsideRTHB\v\n" +
	"\t_auxPriceB\f\n" +
	"\n" +
	"_trailTypeB\r\n" +
	"\v_trailValueB\x0e\n" +
	"\f_trailSpreadB\n" +
	"\n" +
	"\b_sessionB\r\n" +
	"\v_positionIDB\r\n" +
	"\v_expireTime\"\xd1\x02\n" +
	"\x0eCreateOrderRes\x12)\n" +
	"\aretType\x18\x01 \x01(\x0e2\x0f.common.RetTypeR\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12*\n" +
	"\x03s2c\x18\x04 \x01(\v2\x13.CreateOrderRes.S2CH\x02R\x03s2c\x88\x01\x01\x1a\x8c\x01\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12\x1d\n" +
	"\aorderID\x18\x02 \x01(\x04H\x00R\aorderID\x88\x01\x01\x12!\n" +
	"\torderIDEx\x18\x03 \x01(\tH\x01R\torderIDEx\x88\x01\x01B\n" +
	"\n" +
	"\b_orderIDB\f\n" +
	"\n" +
	"_orderIDExB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2cB\tZ\afutu/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_order_proto_goTypes = []any{
	(*FeeReq)(nil),              // 0: FeeReq
	(*FeeRes)(nil),              // 1: FeeRes
	(*NotifyOrder)(nil),         // 2: NotifyOrder
	(*NotifyOrderFill)(nil),     // 3: NotifyOrderFill
	(*CreateOrderReq)(nil),      // 4: CreateOrderReq
	(*CreateOrderRes)(nil),      // 5: CreateOrderRes
	(*FeeReq_C2S)(nil),          // 6: FeeReq.C2S
	(*FeeRes_S2C)(nil),          // 7: FeeRes.S2C
	(*NotifyOrder_S2C)(nil),     // 8: NotifyOrder.S2C
	(*NotifyOrderFill_S2C)(nil), // 9: NotifyOrderFill.S2C
	(*CreateOrderReq_C2S)(nil),  // 10: CreateOrderReq.C2S
	(*CreateOrderRes_S2C)(nil),  // 11: CreateOrderRes.S2C
	(RetType)(0),                // 12: common.RetType
	(*TrdHeader)(nil),           // 13: common.TrdHeader
	(*OrderFee)(nil),            // 14: common.OrderFee
	(*Order)(nil),               // 15: common.Order
	(*OrderFill)(nil),           // 16: common.OrderFill
	(*PacketID)(nil),            // 17: common.PacketID
	(TimeInForce)(0),            // 18: common.TimeInForce
}
var file_order_proto_depIdxs = []int32{
	6,  // 0: FeeReq.c2s:type_name -> FeeReq.C2S
	12, // 1: FeeRes.retType:type_name -> common.RetType
	7,  // 2: FeeRes.s2c:type_name -> FeeRes.S2C
	12, // 3: NotifyOrder.retType:type_name -> common.RetType
	8,  // 4: NotifyOrder.s2c:type_name -> NotifyOrder.S2C
	12, // 5: NotifyOrderFill.retType:type_name -> common.RetType
	9,  // 6: NotifyOrderFill.s2c:type_name -> NotifyOrderFill.S2C
	10, // 7: CreateOrderReq.c2s:type_name -> CreateOrderReq.C2S
	12, // 8: CreateOrderRes.retType:type_name -> common.RetType
	11, // 9: CreateOrderRes.s2c:type_name -> CreateOrderRes.S2C
	13, // 10: FeeReq.C2S.header:type_name -> common.TrdHeader
	13, // 11: FeeRes.S2C.header:type_name -> common.TrdHeader
	14, // 12: FeeRes.S2C.orderFeeList:type_name -> common.OrderFee
	13, // 13: NotifyOrder.S2C.header:type_name -> common.TrdHeader
	15, // 14: NotifyOrder.S2C.order:type_name -> common.Order
	13, // 15: NotifyOrderFill.S2C.header:type_name -> common.TrdHeader
	16, // 16: NotifyOrderFill.S2C.order:type_name -> common.OrderFill
	17, // 17: CreateOrderReq.C2S.packetID:type_name -> common.PacketID
	13, // 18: CreateOrderReq.C2S.header:type_name -> common.TrdHeader
	18, // 19: CreateOrderReq.C2S.timeInForce:type_name -> common.TimeInForce
	13, // 20: CreateOrderRes.S2C.header:type_name -> common.TrdHeader
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_common_proto_init()
	file_order_proto_msgTypes[1].OneofWrappers = []any{}
	file_order_proto_msgTypes[2].OneofWrappers = []any{}
	file_order_proto_msgTypes[3].OneofWrappers = []any{}
	file_order_proto_msgTypes[5].OneofWrappers = []any{}
	file_order_proto_msgTypes[10].OneofWrappers = []any{}
	file_order_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
