// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *订单费用请求
type FeeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *FeeReq_C2S            `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeReq) Reset() {
	*x = FeeReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeReq) ProtoMessage() {}

func (x *FeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeReq.ProtoReflect.Descriptor instead.
func (*FeeReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *FeeReq) GetC2S() *FeeReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

// *订单费用响应
type FeeRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       int32       `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"`
	RetMsg        *string     `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32      `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *FeeRes_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeRes) Reset() {
	*x = FeeRes{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeRes) ProtoMessage() {}

func (x *FeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeRes.ProtoReflect.Descriptor instead.
func (*FeeRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *FeeRes) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *FeeRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *FeeRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *FeeRes) GetS2C() *FeeRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

// * 订单推送
type NotifyOrder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 以下3个字段每条协议都有，注释说明在 InitConnect.proto 中
	RetType       int32            `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"`
	RetMsg        *string          `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32           `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *NotifyOrder_S2C `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrder) Reset() {
	*x = NotifyOrder{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrder) ProtoMessage() {}

func (x *NotifyOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrder.ProtoReflect.Descriptor instead.
func (*NotifyOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyOrder) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *NotifyOrder) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *NotifyOrder) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *NotifyOrder) GetS2C() *NotifyOrder_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type FeeReq_C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`               //交易公共参数头
	OrderIdExList []string               `protobuf:"bytes,2,rep,name=orderIdExList,proto3" json:"orderIdExList,omitempty"` // 服务器订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeReq_C2S) Reset() {
	*x = FeeReq_C2S{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeReq_C2S) ProtoMessage() {}

func (x *FeeReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeReq_C2S.ProtoReflect.Descriptor instead.
func (*FeeReq_C2S) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FeeReq_C2S) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FeeReq_C2S) GetOrderIdExList() []string {
	if x != nil {
		return x.OrderIdExList
	}
	return nil
}

type FeeRes_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`             //交易公共参数头
	OrderFeeList  []*OrderFee            `protobuf:"bytes,2,rep,name=orderFeeList,proto3" json:"orderFeeList,omitempty"` //订单费用列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeRes_S2C) Reset() {
	*x = FeeRes_S2C{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeRes_S2C) ProtoMessage() {}

func (x *FeeRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeRes_S2C.ProtoReflect.Descriptor instead.
func (*FeeRes_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FeeRes_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FeeRes_S2C) GetOrderFeeList() []*OrderFee {
	if x != nil {
		return x.OrderFeeList
	}
	return nil
}

type NotifyOrder_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TrdHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"` //交易公共参数头
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`   //订单结构
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyOrder_S2C) Reset() {
	*x = NotifyOrder_S2C{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyOrder_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyOrder_S2C) ProtoMessage() {}

func (x *NotifyOrder_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyOrder_S2C.ProtoReflect.Descriptor instead.
func (*NotifyOrder_S2C) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NotifyOrder_S2C) GetHeader() *TrdHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *NotifyOrder_S2C) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x1a\fcommon.proto\"\x7f\n" +
	"\x06FeeReq\x12\x1d\n" +
	"\x03c2s\x18\x01 \x01(\v2\v.FeeReq.C2SR\x03c2s\x1aV\n" +
	"\x03C2S\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12$\n" +
	"\rorderIdExList\x18\x02 \x03(\tR\rorderIdExList\"\x89\x02\n" +
	"\x06FeeRes\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12\"\n" +
	"\x03s2c\x18\x04 \x01(\v2\v.FeeRes.S2CH\x02R\x03s2c\x88\x01\x01\x1af\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x124\n" +
	"\forderFeeList\x18\x02 \x03(\v2\x10.common.OrderFeeR\forderFeeListB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2c\"\x82\x02\n" +
	"\vNotifyOrder\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12'\n" +
	"\x03s2c\x18\x04 \x01(\v2\x10.NotifyOrder.S2CH\x02R\x03s2c\x88\x01\x01\x1aU\n" +
	"\x03S2C\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.common.TrdHeaderR\x06header\x12#\n" +
	"\x05order\x18\x02 \x01(\v2\r.common.OrderR\x05orderB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2cB\tZ\afutu/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_proto_goTypes = []any{
	(*FeeReq)(nil),          // 0: FeeReq
	(*FeeRes)(nil),          // 1: FeeRes
	(*NotifyOrder)(nil),     // 2: NotifyOrder
	(*FeeReq_C2S)(nil),      // 3: FeeReq.C2S
	(*FeeRes_S2C)(nil),      // 4: FeeRes.S2C
	(*NotifyOrder_S2C)(nil), // 5: NotifyOrder.S2C
	(*TrdHeader)(nil),       // 6: common.TrdHeader
	(*OrderFee)(nil),        // 7: common.OrderFee
	(*Order)(nil),           // 8: common.Order
}
var file_order_proto_depIdxs = []int32{
	3, // 0: FeeReq.c2s:type_name -> FeeReq.C2S
	4, // 1: FeeRes.s2c:type_name -> FeeRes.S2C
	5, // 2: NotifyOrder.s2c:type_name -> NotifyOrder.S2C
	6, // 3: FeeReq.C2S.header:type_name -> common.TrdHeader
	6, // 4: FeeRes.S2C.header:type_name -> common.TrdHeader
	7, // 5: FeeRes.S2C.orderFeeList:type_name -> common.OrderFee
	6, // 6: NotifyOrder.S2C.header:type_name -> common.TrdHeader
	8, // 7: NotifyOrder.S2C.order:type_name -> common.Order
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	file_common_proto_init()
	file_order_proto_msgTypes[1].OneofWrappers = []any{}
	file_order_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
