// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: sub.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *订阅交易推送请求
type SubAccPushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	C2S           *SubAccPushReq_C2S     `protobuf:"bytes,1,opt,name=c2s,proto3" json:"c2s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAccPushReq) Reset() {
	*x = SubAccPushReq{}
	mi := &file_sub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccPushReq) ProtoMessage() {}

func (x *SubAccPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccPushReq.ProtoReflect.Descriptor instead.
func (*SubAccPushReq) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{0}
}

func (x *SubAccPushReq) GetC2S() *SubAccPushReq_C2S {
	if x != nil {
		return x.C2S
	}
	return nil
}

// *订阅交易推送响应
type SubAccPushRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetType       int32                  `protobuf:"varint,1,opt,name=retType,proto3" json:"retType,omitempty"` //RetType,返回结果
	RetMsg        *string                `protobuf:"bytes,2,opt,name=retMsg,proto3,oneof" json:"retMsg,omitempty"`
	ErrCode       *int32                 `protobuf:"varint,3,opt,name=errCode,proto3,oneof" json:"errCode,omitempty"`
	S2C           *SubAccPushRes_S2C     `protobuf:"bytes,4,opt,name=s2c,proto3,oneof" json:"s2c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAccPushRes) Reset() {
	*x = SubAccPushRes{}
	mi := &file_sub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccPushRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccPushRes) ProtoMessage() {}

func (x *SubAccPushRes) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccPushRes.ProtoReflect.Descriptor instead.
func (*SubAccPushRes) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{1}
}

func (x *SubAccPushRes) GetRetType() int32 {
	if x != nil {
		return x.RetType
	}
	return 0
}

func (x *SubAccPushRes) GetRetMsg() string {
	if x != nil && x.RetMsg != nil {
		return *x.RetMsg
	}
	return ""
}

func (x *SubAccPushRes) GetErrCode() int32 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return 0
}

func (x *SubAccPushRes) GetS2C() *SubAccPushRes_S2C {
	if x != nil {
		return x.S2C
	}
	return nil
}

type SubAccPushReq_C2S struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccIDList     []uint64               `protobuf:"varint,1,rep,packed,name=accIDList,proto3" json:"accIDList,omitempty"` //要接收推送数据的业务账号列表，全量非增量，即使用者请每次传需要接收推送数据的所有业务账号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAccPushReq_C2S) Reset() {
	*x = SubAccPushReq_C2S{}
	mi := &file_sub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccPushReq_C2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccPushReq_C2S) ProtoMessage() {}

func (x *SubAccPushReq_C2S) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccPushReq_C2S.ProtoReflect.Descriptor instead.
func (*SubAccPushReq_C2S) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SubAccPushReq_C2S) GetAccIDList() []uint64 {
	if x != nil {
		return x.AccIDList
	}
	return nil
}

type SubAccPushRes_S2C struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAccPushRes_S2C) Reset() {
	*x = SubAccPushRes_S2C{}
	mi := &file_sub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccPushRes_S2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccPushRes_S2C) ProtoMessage() {}

func (x *SubAccPushRes_S2C) ProtoReflect() protoreflect.Message {
	mi := &file_sub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccPushRes_S2C.ProtoReflect.Descriptor instead.
func (*SubAccPushRes_S2C) Descriptor() ([]byte, []int) {
	return file_sub_proto_rawDescGZIP(), []int{1, 0}
}

var File_sub_proto protoreflect.FileDescriptor

const file_sub_proto_rawDesc = "" +
	"\n" +
	"\tsub.proto\"Z\n" +
	"\rSubAccPushReq\x12$\n" +
	"\x03c2s\x18\x01 \x01(\v2\x12.SubAccPushReq.C2SR\x03c2s\x1a#\n" +
	"\x03C2S\x12\x1c\n" +
	"\taccIDList\x18\x01 \x03(\x04R\taccIDList\"\xb6\x01\n" +
	"\rSubAccPushRes\x12\x18\n" +
	"\aretType\x18\x01 \x01(\x05R\aretType\x12\x1b\n" +
	"\x06retMsg\x18\x02 \x01(\tH\x00R\x06retMsg\x88\x01\x01\x12\x1d\n" +
	"\aerrCode\x18\x03 \x01(\x05H\x01R\aerrCode\x88\x01\x01\x12)\n" +
	"\x03s2c\x18\x04 \x01(\v2\x12.SubAccPushRes.S2CH\x02R\x03s2c\x88\x01\x01\x1a\x05\n" +
	"\x03S2CB\t\n" +
	"\a_retMsgB\n" +
	"\n" +
	"\b_errCodeB\x06\n" +
	"\x04_s2cB\tZ\afutu/pbb\x06proto3"

var (
	file_sub_proto_rawDescOnce sync.Once
	file_sub_proto_rawDescData []byte
)

func file_sub_proto_rawDescGZIP() []byte {
	file_sub_proto_rawDescOnce.Do(func() {
		file_sub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub_proto_rawDesc), len(file_sub_proto_rawDesc)))
	})
	return file_sub_proto_rawDescData
}

var file_sub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sub_proto_goTypes = []any{
	(*SubAccPushReq)(nil),     // 0: SubAccPushReq
	(*SubAccPushRes)(nil),     // 1: SubAccPushRes
	(*SubAccPushReq_C2S)(nil), // 2: SubAccPushReq.C2S
	(*SubAccPushRes_S2C)(nil), // 3: SubAccPushRes.S2C
}
var file_sub_proto_depIdxs = []int32{
	2, // 0: SubAccPushReq.c2s:type_name -> SubAccPushReq.C2S
	3, // 1: SubAccPushRes.s2c:type_name -> SubAccPushRes.S2C
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sub_proto_init() }
func file_sub_proto_init() {
	if File_sub_proto != nil {
		return
	}
	file_sub_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub_proto_rawDesc), len(file_sub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sub_proto_goTypes,
		DependencyIndexes: file_sub_proto_depIdxs,
		MessageInfos:      file_sub_proto_msgTypes,
	}.Build()
	File_sub_proto = out.File
	file_sub_proto_goTypes = nil
	file_sub_proto_depIdxs = nil
}
